<?php

use Drupal\Core\Form\FormStateInterface;

function test2_form_system_site_information_settings_alter(&$form, &$form_state, $form_id)
{
  $service_config = \Drupal::service('config.factory')->getEditable('foo.bar');

  $num_names = $service_config->get('count');
  if ($num_names === NULL) {
    $num_names = 1;
    $service_config->set('count', 1)->save();
  }
  $form['names_fieldset'] = [
    '#type' => 'fieldset',
    '#title' => 'Site name',
    '#prefix' => '<div id="names-fieldset-wrapper">',
    '#suffix' => '</div>',
  ];
  $all_info = $service_config->get('all_info');
  //to be that elements
  foreach ($all_info as $key => $value) {
    $t[] = $key;
  }
  for ($i = 0; $i < $num_names; $i++) {

    $form['names_fieldset'][$i] = [
      '#type' => 'fieldset',
      '#title' => 'Site ' . ' ' . ($i + 1),
    ];
    $form['names_fieldset'][$i]['name' . $t[$i]] = [
      '#type' => 'textfield',
      '#title' => 'Name',
      '#required_but_empty' => 'Please enter Name',
      "#default_value" => $all_info [$t[$i]]['name'],
//      '#required' => TRUE,

    ];
    $form['names_fieldset'][$i]['link' . $t[$i]] = [
      '#type' => 'textfield',
      '#title' => 'Link',
      '#required_but_empty' => 'Please enter Link',
      "#default_value" => $all_info[$t[$i]]['link'],
//      '#required' => TRUE,

    ];
    $form['names_fieldset'][$i]['actions']['remove_name'] = [
      '#type' => 'submit',
      '#value' => 'Remove ' . ($i + 1),
      '#submit' => ['removeCallback'],
      '#name' => $t[$i]+1,
      '#ajax' => [
        'callback' => 'addmoreSiteCallback',
        'wrapper' => 'names-fieldset-wrapper',
      ],
      '#executes_submit_callback' => TRUE,
      '#default_value' => $i,
      "#weight" => $i,
    ];
  }
//  dump($service_config);


  $form['names_fieldset']['actions'] = [
    '#type' => 'actions',
  ];
  $form['actions']['#type'] = 'actions';
  $form['#submit'][] = 'upup_taxonomy_form_submit';
  $form['names_fieldset']['actions']['add_name'] = [
    '#type' => 'submit',
    '#value' => 'Add ',
    '#submit' => ['addOneBlock'],
    '#ajax' => [
      'callback' => 'addmoreSiteCallback',
      'wrapper' => 'names-fieldset-wrapper',
    ],
  ];
}

//remove block if block count > 1
function removeCallback(array &$form, FormStateInterface $form_state)
{
  $service_config = \Drupal::service('config.factory')->getEditable('foo.bar');
  $name_field = $service_config->get('count');
  $service_config->set('count', $name_field - 1);
  //that btn click
  $service_config->set('btn_click', $form_state->getTriggeringElement())->save();
  $res = $service_config->get('btn_click.#name');
  $res--;
  $service_config->clear("all_info.$res")->save();
  $service_config->set('count', $name_field - 1);
  //in the ajax query and reload
  $form_state->setRebuild();
}

function upup_taxonomy_form_submit(&$form, FormStateInterface $form_state)
{
  $service_config = \Drupal::configFactory()->getEditable('foo.bar');

  //nayuma qani hat element ka dra mej kara lini 3,4,7,8
  // es vercnumem dranq vor heto form-ic name3 vercnem
  foreach ($service_config->get('all_info') as $key => $value) {
    $t[] = $key;
  }

  //es en depqi hamara vor ete nora sarqum in@ der dranq chi tarel lcrel
  //orinak karam unenam 5 hat sarqac 2 hatel sarqem mej@ ban grem
  // der inq@ chi tanum yndex lcnum dra hamar es avelacnumem 6,7(2hat avel)
  // vor $t[$count] et elementi name-ov vercnem
  for ($j = count($t); $j < $service_config->get('count'); $j++) {
    if (!isset($t[$j])) {
      $t[] = $j;
    }
  }
  //tvyalmer@ mejnm lcnum u uxarkum db bayc skzbum pustoya
  $all_info = [];
  //bolor@ jnjumem noric lcnumem
  $service_config->set('all_info', $all_info)->save();
  $count = 0;

  //add info in db
  for ($i = 0; $i < count($form['names_fieldset']); $i++) {
    if ($form['names_fieldset'][$i] > 0) {
      $all_info [$count]['name'] = $form['names_fieldset'][$i]['name' . $t[$count]]['#value'];
      $all_info [$count]['link'] = $form['names_fieldset'][$i]['link' . $t[$count]]['#value'];
      $count++;
    }
  }
  $service_config->set('all_info', $all_info)->save();
}

//add element in db
function addOneBlock(array &$form, FormStateInterface $form_state)
{
  $service_config = \Drupal::service('config.factory')->getEditable('foo.bar');
  $name_field = $service_config->get('count');
  $add_button = $name_field + 1;
  $service_config->set('count', $add_button)->save();
  foreach ($service_config->get("all_info") as $key => $value) {
    $max_res[] = $key;
  }

  $service_config->set('all_info.' . (max($max_res) + 1), array('name' => '' . (max($max_res) + 1), 'link' => '' . (max($max_res) + 1)))->save();
  //in the ajax query and reload
  $form_state->setRebuild();
}

//return all form info
function addmoreSiteCallback(array &$form)
{
  return $form['names_fieldset'];
}




